language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- openssl aes-256-cbc -K $encrypted_e55aacca67f1_key -iv $encrypted_e55aacca67f1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mysql -e "create database if not exists test default charset utf8;" -uroot
deploy:
  provider: gae
  project: coduno
