language: java

notifications:
  email: false
  slack:
    secure: "TU6gN0h07a/+H8I3EzNLuMv9UljB/c5MasRIB32ZiFni+eEj8III6C3Xf0m+uGKx5FeA/22CItE6K7PkeD1R4erb77uruhSn9Ngh1C5m+hs5+2Uj4Ocpf4PkFYKTysxMNT+0pblD0qFzTb6NQiict/3H01HZxlCuXuCVw0rJ/fuTEhQ33MLAqNCPBTj6XlAEuZfxsVLq49tXXW5sTaD7kBf+yHvAuws81UYdLmQKaRrqtH8PT5DfICRGQsz9lrh4gxiupURGusg1xldjIwjnK9BsQRxnjVD4hHurAEWvx4wwYBL816JJNXaSiyKUkYx7pqshjtqw8PtI5R6E59JP/fgGc2dS0tE6Ar/Y2CT3R5eHhI2OGbD90y3GIAgceFCHGYsWbuc5Bx89C0205CEY6S0o4DDKnb/OATS1wkoeObdkbpPpDO46qumJ6gFweMqhVphGR9VDRbpph4VWsb7FVLF1xsd40J8uQp/FN/FDslGLjKqhAvCG26tH2bbjlyG/AQyShujLwx3mvYLZwppyBkFdh8IjmsXTxRydrB4K88W/JCQDsJBru5jsWmPYQxqqpOyXvo5JSY75I0Ya4IJgxdTveu8pnLLjlCpY7eNUDPIYA84X+BlOrO7B82HCoMU0ABs4JWgFh+szXzwOMrtbfekX0NE3VonK6TVMI92uBkg="

jdk:
  - oraclejdk8

services:
  - mysql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - $(! $TRAVIS_SECURE_ENV_VARS) || (openssl aes-256-cbc -K $encrypted_e55aacca67f1_key -iv $encrypted_e55aacca67f1_iv
    -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar)
  - $(! $TRAVIS_SECURE_ENV_VARS) || ( if [ "$TRAVIS_BRANCH" == "master" ]; then tar xvf secrets-prod.tar; else tar xvf secrets-lab.tar; sed -i '/SPRING_PROFILES_ACTIVE/s/$/,lab/' Dockerfile; fi; rm secrets*.tar )
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
  - mysql -u root -e "create database if not exists test default charset utf8;"

before_deploy: ./gradlew bootRepackage

deploy:
  - provider: gae
    project: coduno
    skip_cleanup: true
    on:
      branch: master
  - provider: gae
    project: coduno-lab
    skip_cleanup: true
    on:
      branch: dev
