language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - $(! $TRAVIS_SECURE_ENV_VARS) || (openssl aes-256-cbc -K $encrypted_e55aacca67f1_key -iv $encrypted_e55aacca67f1_iv
    -in secrets.tar.enc -out secrets.tar -d && tar xvf secrets.tar)
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost'"
  - mysql -u root -e "create database if not exists test default charset utf8;"

script: ./gradlew build

deploy:
  provider: gae
  project: coduno
  skip_cleanup: true
