coduno:
  url: https://app.cod.uno
  mail:
    from: noreply@cod.uno

spring:
  application.name: Coduno Platform

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_platform
    username: platform
    password:

  jpa:
     show-sql: false
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate:
       ddl-auto: validate

  jackson:
    serialization:
      write_dates_as_timestamps: false
