spring:
  application.name: Coduno Platform
  profiles.active: development

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_platform
    username: platform
    password:

  jpa:
     show-sql: false
     hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       naming_strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
       ddl-auto: update

  thymeleaf:
     cache: false
