coduno:
  url: https://app.cod.uno
  runtime:
    url: https://runtime.cod.uno
  codingcontest_url: https://codingcontest.catalysts.cc
  mail:
    from: noreply@cod.uno
  invite:
    expire: P30D
  template:
    expire: PT2H
    bucket: coduno-templates
  submission:
    bucket: coduno-submissions
  tests:
    bucket: coduno-tests
  instructions:
    bucket: coduno
  geolocation:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz

spring:
  application.name: Coduno Platform

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_platform
    username: platform
    password:

  jpa:
     show-sql: false
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
     hibernate:
       ddl-auto: validate
     properties:
       hibernate.id.new_generator_mappings: false

  jackson:
    serialization:
      write_durations_as_timestamps: true
      # TODO - check why write_dates_as_timestamps overrides write_durations_as_timestamps
      write_dates_as_timestamps: true

  social:
    facebook:
      app-id: id
      app-secret: secret
    google:
      app-id: id
      app-secret: secret
    github:
      app-id: id
      app-secret: secret
    linkedin:
      app-id: id
      app-secret: secret

flyway:
  sql-migration-prefix: ""
  out-of-order: true

multipart:
  maxFileSize: 16MB
  maxRequestSize: 16MB

endpoints:
  health:
    path: /_ah/health

# til gmail is fixed
management:
  health:
    mail:
      enabled: false
