coduno:
  url: http://localhost:6060
  runtime:
    url: http://localhost:8081
  codingcontest_url: https://codingcontest.lab.catalysts.cc
  mail:
    from: noreply@cod.uno
  invite:
    expire: P30D
  storage:
    gcs:
      accountId: platform-gcs@coduno.iam.gserviceaccount.com
      pkcs12: ./service-account.p12
      buckets:
        submissions: coduno-dev
        templates: coduno-templates

spring:
  jpa:
    hibernate:
      ddl-auto: update