spring:
  profiles.active: test

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: travis
    password:

#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:public;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";

#  jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#     hibernate:
#       ddl-auto: validate

#flyway:
#  schemas: PUBLIC