coduno:
  storage:
    gcs:
      accountId: platform-gcs@coduno.iam.gserviceaccount.com
      pkcs12: /gcs-service-account.p12

spring:
  profiles.active: appengine

  mail:
    host: smtp.mailgun.org
    port: 2525
    username: x
    password: x
    test-connection: false
    properties:
      mail.smtp.starttls.enable: true


  datasource:
    driverClassName: org.mariadb.jdbc.Driver
